SHELL_FILE_ENV_PATH="$HOME/.zshenv"

echo '# Github credentials' >> $SHELL_FILE_ENV_PATH
echo 'export GITHUB_USERNAME="YOUR_USER_HERE_MY_DUDE"' >> $SHELL_FILE_ENV_PATH
echo 'export GITHUB_ACCESS_TOKEN_READ_PACKAGES="YOUR_KEY_HERE_MY_DUDE"' >> $SHELL_FILE_ENV_PATH

