SHELL_FILE_ENV_PATH="$HOME/.zshenv"

echo '# Recognized by all the AWS SDKs and CLI ' >> $SHELL_FILE_ENV_PATH
echo 'export AWS_ACCESS_KEY_ID="YOUR_KEY_HERE_MY_DUDE"' >> $SHELL_FILE_ENV_PATH
echo 'export AWS_SECRET_ACCESS_KEY="YOUR_KEY_HERE_MY_DUDE"' >> $SHELL_FILE_ENV_PATH

echo >> $SHELL_FILE_ENV_PATH

echo '# Only recognized by Java SDK' >> $SHELL_FILE_ENV_PATH
echo 'export AWS_ACCESS_KEY="YOUR_KEY_HERE_MY_DUDE"' >> $SHELL_FILE_ENV_PATH
echo 'export AWS_SECRET_KEY="YOUR_KEY_HERE_MY_DUDE"' >> $SHELL_FILE_ENV_PATH

echo >> $SHELL_FILE_ENV_PATH

echo '# Github credentials' >> $SHELL_FILE_ENV_PATH
echo 'export GITHUB_USERNAME="YOUR_USER_HERE_MY_DUDE"' >> $SHELL_FILE_ENV_PATH
echo 'export GITHUB_ACCESS_TOKEN_READ_PACKAGES="YOUR_KEY_HERE_MY_DUDE"' >> $SHELL_FILE_ENV_PATH

